-- ─────────────────────────────────────────────────────────────────────────
-- 2026-07-31 · Seværdigheder — katalog over oplevelser nær Castillo del Alma
--
-- Én række pr. seværdighed. Alle tekster ligger i JSONB-kolonnen `indhold`
-- med samme nøglemønster som gay_content: dansk i `nøgle`, engelsk i
-- `nøgle_en`. Det betyder, at admin-editoren, oversætterknappen og
-- fallback-logikken virker præcis som på de øvrige sider — men uden at der
-- skal oprettes en ny tabel for hver ny seværdighed.
--
-- Siden /sevaerdigheder/<slug> (og /en/sevaerdigheder/<slug>) læser slug'en
-- ud af adressen og henter den matchende række.
--
-- RLS følger samme mønster som de øvrige indholdstabeller efter fase 1:
-- alle må LÆSE (siden skal virke for besøgende), kun rollen 'authenticated'
-- må SKRIVE (admin er logget ind med en ægte Supabase-session).
-- RØR IKKE RLS på betalings-/kunde-tabeller.
--
-- Køres i Supabase SQL Editor. Idempotent — kan køres flere gange.
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists public.sevaerdigheder (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,
  titel       text,
  titel_en    text,
  aktiv       boolean not null default true,
  sort_orden  integer not null default 0,
  indhold     jsonb   not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Opslaget på siden sker altid på slug + aktiv
create index if not exists sevaerdigheder_slug_idx   on public.sevaerdigheder (slug);
create index if not exists sevaerdigheder_aktiv_idx  on public.sevaerdigheder (aktiv, sort_orden);

-- updated_at vedligeholdes af databasen, så sitemappets <lastmod> altid
-- er sand — også når indholdet rettes fra admin.
create or replace function public.sevaerdigheder_touch()
returns trigger language plpgsql as $fn$
begin
  new.updated_at = now();
  return new;
end;
$fn$;

drop trigger if exists sevaerdigheder_touch_trg on public.sevaerdigheder;
create trigger sevaerdigheder_touch_trg
  before update on public.sevaerdigheder
  for each row execute function public.sevaerdigheder_touch();

-- Ryd eventuelle gamle policies, så filen kan køres igen uden fejl,
-- og slå RLS til. Samme fremgangsmåde som i RLS fase 1.
DO $$
DECLARE
  p record;
BEGIN
  FOR p IN
    SELECT policyname FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'sevaerdigheder'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.sevaerdigheder', p.policyname);
  END LOOP;
END $$;

ALTER TABLE public.sevaerdigheder ENABLE ROW LEVEL SECURITY;

CREATE POLICY "alle_maa_laese" ON public.sevaerdigheder
  FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY "kun_admin_maa_skrive" ON public.sevaerdigheder
  FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

comment on table public.sevaerdigheder is
  'Katalog over seværdigheder og oplevelser nær Castillo del Alma. Én række '
  'pr. side; alle tekster i JSONB-kolonnen indhold (nøgler uden suffiks er '
  'danske, _en er engelske). Vises på /sevaerdigheder/<slug> og '
  '/en/sevaerdigheder/<slug>. Redigeres i admin under Sprog & Indhold → Seværdigheder.';


-- ── Første seværdighed: Caminito del Rey ─────────────────────────────────
-- `do nothing` er med vilje: kører du filen igen, overskrives dine egne
-- rettelser i admin ikke. Vil du nulstille siden helt, så slet rækken
-- først og kør filen igen.

insert into public.sevaerdigheder (slug, titel, titel_en, aktiv, sort_orden, indhold) values
  ('caminito-del-rey',
   'Caminito del Rey',
   'Caminito del Rey',
   true,
   10,
   '{
  "seo_title": "Caminito del Rey — guide, billetter og praktisk info | Castillo del Alma",
  "seo_desc": "Alt om Caminito del Rey: rute, billetter, parkering, shuttlebus og bedste årstid. Kun 45 minutters kørsel fra Castillo del Alma i Mollina, Málaga.",
  "seo_title_en": "Caminito del Rey — guide, tickets and practical info | Castillo del Alma",
  "seo_desc_en": "Everything about the Caminito del Rey: the route, tickets, parking, shuttle bus and best season. Just 45 minutes from Castillo del Alma in Mollina, Málaga.",
  "nav_back": "← Tilbage til forsiden",
  "nav_back_en": "← Back to home",
  "footer_copy": "© 2026 Castillo del Alma · Mollina, Málaga · Alle rettigheder forbeholdes",
  "footer_copy_en": "© 2026 Castillo del Alma · Mollina, Málaga · All rights reserved",
  "nav_links": "[{\"tekst\": \"Oplevelsen\", \"tekst_en\": \"The experience\", \"link\": \"#sec-intro\", \"vis\": \"1\"}, {\"tekst\": \"Historien\", \"tekst_en\": \"History\", \"link\": \"#sec-historie\", \"vis\": \"1\"}, {\"tekst\": \"Naturen\", \"tekst_en\": \"Nature\", \"link\": \"#sec-natur\", \"vis\": \"1\"}, {\"tekst\": \"Praktisk\", \"tekst_en\": \"Practical\", \"link\": \"#sec-praktisk\", \"vis\": \"1\"}, {\"tekst\": \"FAQ\", \"tekst_en\": \"FAQ\", \"link\": \"#sec-faq\", \"vis\": \"1\"}, {\"tekst\": \"Lej ejendommen\", \"tekst_en\": \"Rent the estate\", \"link\": \"/udlejning\", \"vis\": \"1\"}]",
  "hero_eyebrow": "Ardales · Málaga · 45 minutter fra Castillo del Alma",
  "hero_eyebrow_en": "Ardales · Málaga · 45 minutes from Castillo del Alma",
  "hero_h1": "Caminito<br>del Rey",
  "hero_h1_en": "Caminito<br>del Rey",
  "hero_lede": "Hængende gangbroer mere end hundrede meter over Guadalhorce-floden — en af Europas mest spektakulære vandreruter, en kort køretur fra vinejendommen.",
  "hero_lede_en": "Walkways suspended more than a hundred metres above the Guadalhorce river — one of Europe''s most spectacular hikes, a short drive from the wine estate.",
  "hero_scroll": "Oplevelsen",
  "hero_scroll_en": "The experience",
  "hero_image": "",
  "social_image": "",
  "vis_hero_stribe": "1",
  "hero_meta": "[{\"da\": [\"7,7 km rute\"], \"en\": [\"7.7 km route\"]}, {\"da\": [\"2½–4 timers vandring\"], \"en\": [\"2½–4 hour hike\"]}, {\"da\": [\"105 meter over floden\"], \"en\": [\"105 metres above the river\"]}, {\"da\": [\"45 min fra Castillo del Alma\"], \"en\": [\"45 min from Castillo del Alma\"]}]",
  "intro_label": "Oplevelsen",
  "intro_label_en": "The experience",
  "intro_h2": "En uforglemmelig oplevelse i hjertet af <em>Andalusien</em>",
  "intro_h2_en": "An unforgettable experience in the heart of <em>Andalusia</em>",
  "intro_lede": "Forestil dig, at du står på en smal gangbro, mens en dyb kløft åbner sig mere end hundrede meter under dine fødder.",
  "intro_lede_en": "Imagine standing on a narrow walkway while a deep gorge opens more than a hundred metres beneath your feet.",
  "intro_text": "Solen varmer de gyldne kalkstensklipper, en let brise bevæger sig gennem slugten, og højt over dig svæver gåsegribbene næsten lydløst på de varme luftstrømme. Foran dig snor stien sig langs den stejle bjergside, og bag hvert sving venter endnu en udsigt, som er smukkere end den forrige.\nVelkommen til <b>Caminito del Rey</b> — en af Europas mest spektakulære naturoplevelser.\nKun 45 minutters kørsel fra <b>Castillo del Alma</b> ligger den berømte vandrerute, som hvert år tiltrækker besøgende fra hele verden. Det er en oplevelse, der kombinerer rå natur, fascinerende historie og moderne ingeniørkunst på en måde, som kun få steder kan matche.\nSelvom billederne af de svævende gangbroer er blevet ikoniske, er Caminito del Rey meget mere end de dramatiske passager. Vandreturen begynder gennem en fredelig fyrreskov, hvor duften af harpiks og vilde middelhavsurter fylder luften. Langsomt åbner landskabet sig, og de første udsigter over kløften viser sig mellem træerne.",
  "intro_text_en": "The sun warms the golden limestone cliffs, a light breeze moves through the ravine, and high above you griffon vultures glide almost silently on the thermals. Ahead, the path winds along the steep mountainside, and behind every bend waits another view more beautiful than the last.\nWelcome to the <b>Caminito del Rey</b> — one of Europe''s most spectacular natural experiences.\nJust a 45-minute drive from <b>Castillo del Alma</b> lies the famous walkway that draws visitors from all over the world each year. It combines raw nature, fascinating history and modern engineering in a way few places can match.\nAlthough the images of the suspended walkways have become iconic, the Caminito del Rey is far more than its dramatic passages. The walk begins through a peaceful pine forest, where the scent of resin and wild Mediterranean herbs fills the air. Slowly the landscape opens, and the first views over the gorge appear between the trees.",
  "intro_image": "",
  "intro_billedtekst": "Caminito del Rey · Ardales · Málaga",
  "intro_billedtekst_en": "Caminito del Rey · Ardales · Málaga",
  "historie_label": "Historien",
  "historie_label_en": "History",
  "historie_h2": "En sti bygget til arbejdere — <em>ikke til turister</em>",
  "historie_h2_en": "A path built for workers — <em>not for tourists</em>",
  "historie_text": "De færreste ved, at Caminito del Rey aldrig blev bygget som turistattraktion.\nI begyndelsen af 1900-tallet var området centrum for et af Spaniens største vandkraftprojekter. Arbejderne havde brug for en sikker forbindelse mellem dæmningerne og kraftværkerne, og derfor blev den smalle betonsti bygget direkte ind i klipperne mellem 1901 og 1905.\nArbejdet var enormt krævende. Materialer måtte fires ned fra toppen af bjergene, mens håndværkerne arbejdede hængende i reb højt over floden. Når man ser den gamle sti i dag, er det næsten umuligt ikke at blive imponeret over den ingeniørkunst og det mod, der gjorde projektet muligt.\nI 1921 besøgte <b>Kong Alfonso XIII</b> området for at indvie den nye Conde del Guadalhorce-dæmning. Under besøget gik han en del af stien, og siden den dag har den båret navnet Caminito del Rey — <em>Kongens Lille Sti</em>.\n<b>Da eventyrerne overtog.</b> Efter årtiers brug begyndte naturen langsomt at tage stien tilbage. Betonen smuldrede, rækværkene forsvandt, og flere steder styrtede hele sektioner sammen. Til sidst stod kun de rustne stålbjælker tilbage, mens den oprindelige gangbro hang som et spøgelse langs klippevæggen. Fotos af folk, der balancerede hen over de ødelagte broer uden sikkerhedsudstyr, gik verden rundt og gjorde ruten berygtet som verdens farligste vandrerute. Efter flere tragiske ulykker blev området lukket.\n<b>Et mesterværk af moderne ingeniørkunst.</b> I stedet valgte man at redde den. Under restaureringen i 2014 og 2015 blev der bygget en helt ny gangbro, som følger den oprindelige rute gennem kløften. Den gamle sti blev bevaret som historisk monument, og flere steder kan man stadig se resterne hænge under den nye konstruktion. Du går på en sikker gangbro med solide rækværk, men lige under dig hænger de originale betonrester som et fascinerende vidnesbyrd om fortiden.",
  "historie_text_en": "Few people know that the Caminito del Rey was never built as a tourist attraction.\nIn the early 1900s the area was the centre of one of Spain''s largest hydroelectric projects. Workers needed a safe connection between the dams and the power stations, and so the narrow concrete path was built directly into the cliffs between 1901 and 1905.\nThe work was enormously demanding. Materials had to be lowered from the mountain tops while the builders worked hanging from ropes high above the river. Seeing the old path today, it is almost impossible not to be impressed by the engineering and the courage that made the project possible.\nIn 1921 <b>King Alfonso XIII</b> visited the area to inaugurate the new Conde del Guadalhorce dam. During the visit he walked part of the path, and from that day it has carried the name Caminito del Rey — <em>the King''s Little Path</em>.\n<b>When the adventurers took over.</b> After decades of use, nature slowly began to reclaim the path. The concrete crumbled, the railings disappeared, and in several places entire sections collapsed. In the end only the rusted steel beams remained, the original walkway hanging like a ghost along the rock face. Photographs of people balancing across the broken bridges without safety equipment travelled the world and made the route notorious as the most dangerous walk on earth. After several tragic accidents the area was closed.\n<b>A masterpiece of modern engineering.</b> Instead, it was saved. During the restoration in 2014 and 2015 an entirely new walkway was built, following the original route through the gorge. The old path was preserved as a historic monument, and in several places you can still see its remains hanging beneath the new structure. You walk on a secure walkway with solid railings, but just below you hang the original concrete remnants — a fascinating testimony to the past.",
  "historie_image": "",
  "historie_billedtekst": "Den oprindelige sti fra 1905",
  "historie_billedtekst_en": "The original path from 1905",
  "natur_label": "Naturen",
  "natur_label_en": "Nature",
  "natur_h2": "Formet gennem <em>millioner af år</em>",
  "natur_h2_en": "Shaped over <em>millions of years</em>",
  "natur_text": "Caminito del Rey ligger midt i naturparken <b>Desfiladero de los Gaitanes</b>, hvor Guadalhorce-floden gennem millioner af år har skåret sig dybere og dybere ned gennem de massive kalkstensbjerge.\nResultatet er et dramatisk landskab med lodrette klippevægge, der flere steder rejser sig næsten 300 meter mod himlen. Når man står på gangbroen, virker klipperne næsten uendelige, mens floden langt under én fortsætter sin rolige vej gennem slugten.\nLyset ændrer sig konstant i løbet af dagen. Om morgenen rammer solen klipperne med et blødt gyldent skær, mens eftermiddagen fremhæver de mange nuancer i kalkstenen. Uanset årstid er udsigten ganske enkelt betagende.\nMange tror, at Caminito del Rey handler om højder. I virkeligheden handler den om natur. Langs stien vokser rosmarin, timian, lavendel og fyrretræer, som fylder luften med duften af Middelhavet. Om foråret dækkes skråningerne af vilde blomster, mens efterårets bløde lys giver landskabet en næsten gylden glød.",
  "natur_text_en": "The Caminito del Rey lies in the middle of the <b>Desfiladero de los Gaitanes</b> nature park, where over millions of years the Guadalhorce river has cut deeper and deeper through the massive limestone mountains.\nThe result is a dramatic landscape of vertical rock walls rising almost 300 metres towards the sky in places. Standing on the walkway, the cliffs seem almost endless, while far below the river continues its calm passage through the ravine.\nThe light changes constantly through the day. In the morning the sun strikes the cliffs with a soft golden glow, while the afternoon brings out the many shades in the limestone. Whatever the season, the view is quite simply breathtaking.\nMany people think the Caminito del Rey is about heights. In reality it is about nature. Along the path grow rosemary, thyme, lavender and pine, filling the air with the scent of the Mediterranean. In spring the slopes are covered in wildflowers, while the soft light of autumn gives the landscape an almost golden glow.",
  "natur_image": "",
  "natur_billedtekst": "Gaitanes-kløften · 300 meter lodret",
  "natur_billedtekst_en": "The Gaitanes gorge · 300 vertical metres",
  "lister_label": "Dyreliv og flora",
  "lister_label_en": "Wildlife and flora",
  "lister_h2": "Hvad du kan få øje på",
  "lister_h2_en": "What to look out for",
  "lister_intro": "Kommer du tidligt om morgenen, er chancen for at opleve dyrelivet størst.",
  "lister_intro_en": "Arrive early in the morning and your chances of seeing wildlife are at their best.",
  "lister_grupper": "[{\"da\": [\"Dyreliv\", \"Gåsegribbe, som ofte svæver tæt over klipperne\\nKongeørn\\nBjerggeder — spansk stenbuk (ibex)\\nUgler\\nFirben og mange sommerfuglearter\"], \"en\": [\"Wildlife\", \"Griffon vultures, often circling close to the cliffs\\nGolden eagle\\nMountain goats — Spanish ibex\\nOwls\\nLizards and many species of butterfly\"]}, {\"da\": [\"Flora\", \"Vild timian\\nRosmarin\\nLavendel\\nMastiktræer\\nAleppofyr\\nJohannesbrødtræer\"], \"en\": [\"Flora\", \"Wild thyme\\nRosemary\\nLavender\\nMastic trees\\nAleppo pine\\nCarob trees\"]}, {\"da\": [\"Landskabet\", \"Naturparken Desfiladero de los Gaitanes\\nLodrette kalkstensvægge på over 300 meter\\nGuadalhorce-floden dybt nede i kløften\\nMillioner af års erosion\"], \"en\": [\"The landscape\", \"Desfiladero de los Gaitanes nature park\\nVertical limestone walls of over 300 metres\\nThe Guadalhorce river deep in the gorge\\nMillions of years of erosion\"]}]",
  "hoej_label": "Højdepunktet",
  "hoej_label_en": "The highlight",
  "hoej_h2": "Den berømte <em>hængebro</em>",
  "hoej_h2_en": "The famous <em>suspension bridge</em>",
  "hoej_text": "Jo længere du kommer, desto mere dramatisk bliver naturen. Klipperne bliver stejlere. Stien smallere. Og udsigten mere imponerende.\nPludselig står du på hængebroen med hundredvis af meter klippe over dig og floden langt nede under dig. Det er her, de fleste stopper op — ikke fordi turen er fysisk krævende, men fordi naturen ganske enkelt fortjener et øjebliks stilhed.",
  "hoej_text_en": "The further you go, the more dramatic the landscape becomes. The cliffs grow steeper. The path narrower. And the view more impressive.\nSuddenly you are standing on the suspension bridge with hundreds of metres of rock above you and the river far below. This is where most people stop — not because the walk is physically demanding, but because the landscape simply deserves a moment of silence.",
  "hoej_punkter": "[{\"da\": [\"35 meter lang\"], \"en\": [\"35 metres long\"]}, {\"da\": [\"Hænger ca. 105 meter over floden\"], \"en\": [\"Suspended about 105 metres above the river\"]}, {\"da\": [\"Gynger let, når man går over\"], \"en\": [\"Sways gently as you cross\"]}, {\"da\": [\"Et af de mest fotograferede steder på hele ruten\"], \"en\": [\"One of the most photographed spots on the whole route\"]}]",
  "hoej_image": "",
  "hoej_billedtekst": "Hængebroen · 105 meter over floden",
  "hoej_billedtekst_en": "The bridge · 105 metres above the river",
  "praktisk_label": "Praktiske detaljer",
  "praktisk_label_en": "Practical details",
  "praktisk_h2": "Alt du skal vide før turen",
  "praktisk_h2_en": "Everything to know before you go",
  "praktisk_intro": "På trods af sit dramatiske udseende er Caminito del Rey i dag en sikker og tilgængelig oplevelse. Det kræver hverken klatreerfaring eller topform — almindelig kondition og gode sko er nok.",
  "praktisk_intro_en": "Despite its dramatic appearance, the Caminito del Rey is today a safe and accessible experience. It requires neither climbing experience nor peak fitness — ordinary condition and good shoes are enough.",
  "praktisk_grupper": "[{\"da\": [\"Adresse\", \"Besøgscenter | Centro de Recepción de Visitantes\\nVej | Puerto de las Atalayas\\nBy | 29550 Ardales (Málaga), Spanien\"], \"en\": [\"Address\", \"Visitor centre | Centro de Recepción de Visitantes\\nRoad | Puerto de las Atalayas\\nTown | 29550 Ardales (Málaga), Spain\"]}, {\"da\": [\"Selve ruten\", \"Samlet længde | ca. 7,7 km\\nGangbroer | ca. 3 km\\nVandretid | 2½–4 timer\\nSværhedsgrad | Let til moderat\\nRetning | Kun én vej — fra nord til syd\\nHøjde over floden | op til ca. 105 meter\"], \"en\": [\"The route\", \"Total length | approx. 7.7 km\\nWalkways | approx. 3 km\\nWalking time | 2½–4 hours\\nDifficulty | Easy to moderate\\nDirection | One way only — north to south\\nHeight above river | up to approx. 105 metres\"]}, {\"da\": [\"Højdepunkter\", \"Spektakulære udsigter over Gaitanes-kløften\\nGlasplatform med frit udsyn ned i kløften\\nLodrette klippevægge\\nGribbe, ørne og andet dyreliv\\nHistoriske tunneler og gamle vandkraftanlæg\"], \"en\": [\"Highlights\", \"Spectacular views over the Gaitanes gorge\\nGlass platform looking straight down into the ravine\\nVertical rock walls\\nVultures, eagles and other wildlife\\nHistoric tunnels and old hydroelectric works\"]}, {\"da\": [\"Billetter\", \"Standardbillet | ca. 10 €\\nGuidet tur | ca. 18 €\\nKøbes på | www.caminitodelrey.info\\nDet anbefales kraftigt at købe billetter flere uger — gerne måneder — i forvejen, især i foråret og efteråret.\"], \"en\": [\"Tickets\", \"Standard ticket | approx. €10\\nGuided tour | approx. €18\\nBuy at | www.caminitodelrey.info\\nBooking several weeks — ideally months — in advance is strongly recommended, especially in spring and autumn.\"]}, {\"da\": [\"Parkering\", \"Besøgscenteret | 2 € pr. dag\\nP1 Nordparkering | tæt ved indgangen\\nBesøgscenterets plads er stor og har shuttlebus direkte til starten. Fra P1 er der ca. 20–35 minutters gang til selve starten afhængigt af ruten gennem tunnelen.\"], \"en\": [\"Parking\", \"Visitor centre | €2 per day\\nP1 North car park | close to the entrance\\nThe visitor centre car park is large and has a shuttle bus directly to the start. From P1 it is a 20–35 minute walk to the start depending on the route through the tunnel.\"]}, {\"da\": [\"Shuttlebus\", \"Pris | 2,50 € pr. person\\nKøretid | ca. 15–20 minutter\\nAfgange | ca. kl. 07.40–20.00\\nDa ruten kun går én vej, kører der shuttlebus mellem slutpunktet og startområdet. Billet købes online eller kontant hos chaufføren — kort accepteres normalt ikke.\"], \"en\": [\"Shuttle bus\", \"Price | €2.50 per person\\nJourney time | approx. 15–20 minutes\\nDepartures | approx. 07:40–20:00\\nAs the route runs one way only, a shuttle bus connects the end point with the starting area. Tickets are bought online or in cash from the driver — cards are usually not accepted.\"]}, {\"da\": [\"Godt at vide\", \"Minimumsalder | 8 år\\nFremmøde | mindst 30 minutter før reservationen\\nSolide lukkede sko er påkrævet\\nKlipklappere og høje hæle er ikke tilladt\\nKæledyr er ikke tilladt\\nHjelm udleveres ved indgangen og er inkluderet i billetten\"], \"en\": [\"Good to know\", \"Minimum age | 8 years\\nArrival | at least 30 minutes before your reservation\\nSturdy closed shoes are required\\nFlip-flops and high heels are not permitted\\nPets are not allowed\\nA helmet is handed out at the entrance and is included in the ticket\"]}, {\"da\": [\"Bedste tidspunkt\", \"Forår | marts–maj\\nEfterår | september–november\\nOm sommeren kan temperaturen let overstige 35 °C, så en tidlig morgen anbefales.\"], \"en\": [\"Best time to visit\", \"Spring | March–May\\nAutumn | September–November\\nIn summer the temperature easily exceeds 35 °C, so an early morning start is recommended.\"]}]",
  "afstande_label": "Sådan kommer du hertil",
  "afstande_label_en": "Getting there",
  "afstande_h2": "Kort vej fra <em>vinejendommen</em>",
  "afstande_h2_en": "A short drive from <em>the estate</em>",
  "afstande_intro": "Castillo del Alma ligger i Mollina, midt i Antequera-bassinet. Herfra er der kort vej til både Caminito del Rey og resten af det indre Andalusien.",
  "afstande_intro_en": "Castillo del Alma sits in Mollina, in the middle of the Antequera basin. From here it is a short drive to the Caminito del Rey and the rest of inland Andalusia.",
  "afstande_items": "[{\"da\": [\"45 min\", \"Castillo del Alma (Mollina)\"], \"en\": [\"45 min\", \"Castillo del Alma (Mollina)\"]}, {\"da\": [\"45 min\", \"Antequera\"], \"en\": [\"45 min\", \"Antequera\"]}, {\"da\": [\"1 time\", \"Málaga centrum\"], \"en\": [\"1 hour\", \"Málaga city centre\"]}, {\"da\": [\"1 time\", \"Málaga Lufthavn\"], \"en\": [\"1 hour\", \"Málaga Airport\"]}]",
  "faq_label": "Spørgsmål",
  "faq_label_en": "Questions",
  "faq_h2": "Før du tager afsted",
  "faq_h2_en": "Before you go",
  "faq_items": "[{\"da\": [\"Hvor lang tid tager Caminito del Rey?\", \"Selve ruten er ca. 7,7 km og tager typisk mellem 2½ og 4 timer. Regn med en halv dag i alt, når parkering, shuttlebus og pauser tælles med.\"], \"en\": [\"How long does the Caminito del Rey take?\", \"The route is about 7.7 km and typically takes between 2½ and 4 hours. Allow half a day in total once parking, the shuttle bus and breaks are included.\"]}, {\"da\": [\"Er det farligt?\", \"Nej. Ruten blev fuldstændig genopbygget i 2014–2015 med brede gangbroer, solide sikkerhedsrækværk og hjelm til alle besøgende. Det gamle ry som verdens farligste vandrerute hører fortiden til.\"], \"en\": [\"Is it dangerous?\", \"No. The route was completely rebuilt in 2014–2015 with wide walkways, solid safety railings and a helmet for every visitor. Its old reputation as the world''s most dangerous walk belongs to the past.\"]}, {\"da\": [\"Skal jeg booke billetter i forvejen?\", \"Ja — det anbefales kraftigt. Billetterne sælges ofte ud flere uger eller måneder i forvejen, især i foråret og efteråret. Køb dem på den officielle hjemmeside, så snart dine datoer ligger fast.\"], \"en\": [\"Do I need to book tickets in advance?\", \"Yes — strongly recommended. Tickets often sell out weeks or months ahead, especially in spring and autumn. Buy them on the official site as soon as your dates are fixed.\"]}, {\"da\": [\"Hvor langt er der fra Castillo del Alma?\", \"Cirka 45 minutters kørsel. Vi hjælper gerne med rute, parkeringsvalg og et godt tidspunkt at tage afsted på, så I undgår både kø og eftermiddagsvarme.\"], \"en\": [\"How far is it from Castillo del Alma?\", \"About a 45-minute drive. We are happy to help with the route, where to park and the best time to set off, so you avoid both the queues and the afternoon heat.\"]}, {\"da\": [\"Er ruten egnet til børn?\", \"Minimumsalderen er 8 år. Børn over den alder klarer normalt turen fint — den er let til moderat og kræver ingen klatreerfaring, men der er højder undervejs.\"], \"en\": [\"Is it suitable for children?\", \"The minimum age is 8. Children above that age normally manage the walk comfortably — it is easy to moderate and requires no climbing experience, though there are heights along the way.\"]}, {\"da\": [\"Hvornår på året er det bedst?\", \"Marts–maj og september–november er de mest behagelige måneder. Om sommeren kan temperaturen let overstige 35 °C, og så bør man tage afsted tidligt om morgenen.\"], \"en\": [\"What is the best time of year?\", \"March–May and September–November are the most comfortable months. In summer temperatures easily exceed 35 °C, so an early morning start is best.\"]}]",
  "flere_label": "Flere oplevelser",
  "flere_label_en": "More experiences",
  "flere_h2": "Andre seværdigheder i nærheden",
  "flere_h2_en": "Other places nearby",
  "flere_intro": "Andalusien byder på meget mere end én vandrerute. Her er flere oplevelser inden for kort køreafstand fra Castillo del Alma.",
  "flere_intro_en": "Andalusia offers far more than one walk. Here are more experiences within a short drive of Castillo del Alma.",
  "cta_h2": "Gør Caminito del Rey til en del af dit ophold",
  "cta_h2_en": "Make the Caminito del Rey part of your stay",
  "cta_text": "Et ophold på Castillo del Alma handler om at opleve Andalusien med alle sanser. Mange af vores gæster fortæller, at netop denne dag bliver et af de stærkeste minder fra deres ferie.",
  "cta_text_en": "A stay at Castillo del Alma is about experiencing Andalusia with all your senses. Many of our guests tell us that this particular day becomes one of the strongest memories of their holiday.",
  "cta_btn": "Se ejendommen",
  "cta_btn_en": "See the estate",
  "cta_link": "/udlejning",
  "strip1_images": "[]",
  "strip1_top": "2",
  "strip1_bund": "2",
  "strip2_images": "[]",
  "strip2_top": "2",
  "strip2_bund": "2",
  "strip3_images": "[]",
  "strip3_top": "2",
  "strip3_bund": "2",
  "sektion_orden": "[\"sec-intro\", \"strip1\", \"sec-historie\", \"sec-natur\", \"sec-lister\", \"strip2\", \"sec-hoejdepunkt\", \"sec-praktisk\", \"sec-afstande\", \"strip3\", \"sec-faq\", \"sec-flere\", \"sec-cta\"]",
  "vis_intro": "1",
  "vis_strip1": "1",
  "vis_historie": "1",
  "vis_natur": "1",
  "vis_lister": "1",
  "vis_strip2": "1",
  "vis_hoejdepunkt": "1",
  "vis_praktisk": "1",
  "vis_afstande": "1",
  "vis_strip3": "1",
  "vis_faq": "1",
  "vis_flere": "1",
  "vis_cta": "1"
}'::jsonb)
on conflict (slug) do nothing;


-- ── Kontrol ──────────────────────────────────────────────────────────────
-- select slug, titel, aktiv, sort_orden, jsonb_object_keys_count
--   from (select slug, titel, aktiv, sort_orden,
--                (select count(*) from jsonb_object_keys(indhold)) as jsonb_object_keys_count
--         from public.sevaerdigheder) t
--  order by sort_orden;


-- ── Tilbagerulning (kør kun bevidst — sletter alt indhold) ───────────────
-- drop trigger if exists sevaerdigheder_touch_trg on public.sevaerdigheder;
-- drop function if exists public.sevaerdigheder_touch();
-- drop table if exists public.sevaerdigheder;
