-- ─────────────────────────────────────────────────────────────────────────
-- 2026-08-04 · Seværdighed: Flamingosøen i Fuente de Piedra
--
-- Én ny række i public.sevaerdigheder. Tabellen, RLS og triggeren er
-- oprettet i sql/2026-07-31-sevaerdigheder.sql — den fil skal være kørt først.
--
-- Siden bliver til /sevaerdigheder/laguna-fuente-de-piedra og /en/sevaerdigheder/laguna-fuente-de-piedra.
--
-- OPRETTES SKJULT (aktiv = false). Alle billedfelter står tomme. Læg
-- billederne ind i admin først, og sæt så Aktiv til.
--
-- Fakta hentet 4. august 2026 fra Junta de Andalucías Ventana del Visitante
-- (knap 1.400 hektar, seks kilometer lang, Andalusiens største indlandssø,
-- vigtigste flamingokoloni på Den Iberiske Halvø og næststørste i Europa, op
-- til 20.000 registrerede ynglepar, forår og tidlig morgen er bedst) samt fra
-- Fuente de Piedras kommune (Centro de Visitantes José Antonio Valverde på
-- Cerro del Palo). Gratis adgang og parkering.
--
-- Sæsonen er det vigtigste på siden: tørrer søen ud om sommeren, flytter
-- fuglene sig. Det står tydeligt frem for at blive gemt væk.
--
-- Køres i Supabase SQL Editor. Idempotent — kan køres flere gange.
-- `on conflict do nothing`: køres filen igen, overskrives senere rettelser
-- i admin ikke. Vil du nulstille siden helt, så slet rækken først.
-- ─────────────────────────────────────────────────────────────────────────

insert into public.sevaerdigheder (slug, titel, titel_en, aktiv, sort_orden, indhold) values
  ('laguna-fuente-de-piedra',
   'Flamingosøen — Fuente de Piedra',
   'The Flamingo Lake — Fuente de Piedra',
   false,
   90,
   '{
  "nav_back": "← Tilbage til forsiden",
  "nav_back_en": "← Back to home",
  "footer_copy": "© 2026 Castillo del Alma · Mollina, Málaga · Alle rettigheder forbeholdes",
  "footer_copy_en": "© 2026 Castillo del Alma · Mollina, Málaga · All rights reserved",
  "hero_image": "",
  "social_image": "",
  "intro_image": "",
  "historie_image": "",
  "natur_image": "",
  "hoej_image": "",
  "intro_billedtekst": "",
  "intro_billedtekst_en": "",
  "historie_billedtekst": "",
  "historie_billedtekst_en": "",
  "natur_billedtekst": "",
  "natur_billedtekst_en": "",
  "hoej_billedtekst": "",
  "hoej_billedtekst_en": "",
  "strip1_images": "[]",
  "strip1_top": "2",
  "strip1_bund": "2",
  "strip2_images": "[]",
  "strip2_top": "2",
  "strip2_bund": "2",
  "strip3_images": "[]",
  "strip3_top": "2",
  "strip3_bund": "2",
  "afstande_label": "Sådan kommer du hertil",
  "afstande_label_en": "Getting there",
  "faq_label": "Spørgsmål",
  "faq_label_en": "Questions",
  "faq_h2": "Før du tager afsted",
  "faq_h2_en": "Before you go",
  "praktisk_label": "Praktiske detaljer",
  "praktisk_label_en": "Practical details",
  "praktisk_h2": "Alt du skal vide før besøget",
  "praktisk_h2_en": "Everything to know before you go",
  "flere_label": "Flere oplevelser",
  "flere_label_en": "More experiences",
  "flere_h2": "Andre seværdigheder i nærheden",
  "flere_h2_en": "Other places nearby",
  "cta_btn": "Se ejendommen",
  "cta_btn_en": "See the estate",
  "cta_link": "/udlejning",
  "lister_label": "",
  "lister_label_en": "",
  "lister_h2": "",
  "lister_h2_en": "",
  "lister_intro": "",
  "lister_intro_en": "",
  "lister_grupper": "[]",
  "hoej_punkter": "[{\"da\": [\"Kikkert er ikke luksus her — besøgscentret låner også ud\"], \"en\": [\"Binoculars are not a luxury here — the visitor centre lends them too\"]}, {\"da\": [\"Den lille lagune inde i selve byen er ofte det nemmeste sted at komme tæt på\"], \"en\": [\"The small lagoon inside the village itself is often the easiest place to get close\"]}, {\"da\": [\"Stierne er flade og korte — omkring en halv time til de nærmeste udsigtspunkter\"], \"en\": [\"The paths are flat and short — about half an hour to the nearest viewpoints\"]}, {\"da\": [\"Der er ingen skygge. Hat og vand om sommeren\"], \"en\": [\"There is no shade. Hat and water in summer\"]}]",
  "sektion_orden": "[\"sec-print1\", \"sec-intro\", \"strip1\", \"sec-historie\", \"sec-natur\", \"sec-lister\", \"strip2\", \"sec-hoejdepunkt\", \"sec-praktisk\", \"sec-afstande\", \"strip3\", \"sec-faq\", \"sec-flere\", \"sec-cta\", \"sec-print4\"]",
  "vis_hero_stribe": "1",
  "vis_intro": "1",
  "vis_strip1": "1",
  "vis_historie": "1",
  "vis_natur": "1",
  "vis_lister": "0",
  "vis_strip2": "1",
  "vis_hoejdepunkt": "1",
  "vis_praktisk": "1",
  "vis_afstande": "1",
  "vis_strip3": "1",
  "vis_faq": "1",
  "vis_flere": "1",
  "vis_cta": "1",
  "vis_historie51": "0",
  "vis_historie52": "0",
  "vis_historie53": "0",
  "vis_historie54": "0",
  "vis_print1": "1",
  "vis_print2": "0",
  "vis_print3": "0",
  "vis_print4": "0",
  "intro_layout": "hoejre",
  "intro_bredde": "normal",
  "historie_layout": "venstre",
  "historie_bredde": "normal",
  "natur_layout": "hoejre",
  "natur_bredde": "normal",
  "hoej_layout": "venstre",
  "hoej_bredde": "normal",
  "seo_title": "Flamingosøen i Fuente de Piedra — 10 minutter fra Mollina | Castillo del Alma",
  "seo_title_en": "The Flamingo Lake at Fuente de Piedra — 10 minutes from Mollina | Castillo del Alma",
  "seo_desc": "Andalusiens største sø og Den Iberiske Halvøs vigtigste flamingokoloni. Bedste årstid, gratis adgang, besøgscenter og hvornår på dagen fuglene står tættest.",
  "seo_desc_en": "Andalusia''s largest lake and the Iberian Peninsula''s most important flamingo colony. Best season, free access, visitor centre and the time of day the birds gather closest.",
  "hero_eyebrow": "Fuente de Piedra · Málaga · Naturreservat",
  "hero_eyebrow_en": "Fuente de Piedra · Málaga · Nature reserve",
  "hero_h1": "Flamingosøen<br>Fuente de Piedra",
  "hero_h1_en": "The Flamingo Lake<br>Fuente de Piedra",
  "hero_lede": "Tyve tusind ynglepar lyserøde flamingoer på en saltsø, der ligger ti minutter fra vores port.",
  "hero_lede_en": "Twenty thousand breeding pairs of pink flamingos on a salt lake, ten minutes from our gate.",
  "hero_scroll": "Søen",
  "hero_scroll_en": "The lake",
  "hero_meta": "[{\"da\": [\"Andalusiens største sø\"], \"en\": [\"Andalusia''s largest lake\"]}, {\"da\": [\"Bedst marts–juni\"], \"en\": [\"Best March–June\"]}, {\"da\": [\"10 minutter fra ejendommen\"], \"en\": [\"10 minutes from the estate\"]}]",
  "intro_label": "Hvad det er",
  "intro_label_en": "What it is",
  "intro_h2": "Vores nærmeste nabo",
  "intro_h2_en": "Our nearest neighbour",
  "intro_lede": "Af alt hvad vi sender gæster ud til, ligger det her tættest. Ti minutter ad landevejen, og så står man ved en sø på næsten 1.400 hektar med lyserøde fugle så langt øjet rækker.",
  "intro_lede_en": "Of everything we send guests out to see, this is the closest. Ten minutes down the country road, and you are standing at a lake of almost 1,400 hectares with pink birds as far as you can see.",
  "intro_text": "Fuente de Piedra er den største indlandssø i Andalusien — seks kilometer lang, lavvandet og salt. Netop saltet er grunden til, at flamingoerne kommer: det giver de små krebsdyr, som farver fuglene lyserøde.\nSøen huser den vigtigste ynglekoloni af flamingoer på Den Iberiske Halvø og den næststørste i Europa. I gode år er der registreret op mod 20.000 ynglepar.\nAdgangen er gratis, parkeringen er gratis, og der er afmærkede stier og skjul at kigge fra. Man behøver hverken booke eller planlægge — det er en udflugt, man kan tage på en indskydelse.",
  "intro_text_en": "Fuente de Piedra is the largest inland lake in Andalusia — six kilometres long, shallow and salt. The salt is precisely why the flamingos come: it supports the tiny crustaceans that turn the birds pink.\nThe lake holds the most important flamingo breeding colony on the Iberian Peninsula and the second most important in Europe. In good years up to 20,000 breeding pairs have been recorded.\nAccess is free, parking is free, and there are marked paths and hides to watch from. There is nothing to book and nothing to plan — this is an outing you can take on a whim.",
  "historie_label": "Historien",
  "historie_label_en": "The history",
  "historie_h2": "Fra saltværk til reservat",
  "historie_h2_en": "From saltworks to reserve",
  "historie_text": "Saltet i søen har været udnyttet siden romertiden og helt frem til 1950''erne. Man byggede diger, ledte vandet væk og lod solen gøre resten.\nDigerne står der endnu. I dag bruger fuglene dem til at bygge rede på — de ligger hævet over vandet, præcis hvad en flamingo har brug for. Et industrianlæg er blevet til det, der holder kolonien i live.\nHver sommer ringmærkes ungfuglene, og det er blevet en begivenhed, som frivillige rejser langvejs fra for at deltage i.",
  "historie_text_en": "The lake''s salt was worked from Roman times right up to the 1950s. Dykes were built, water was drained off, and the sun did the rest.\nThe dykes are still there. Today the birds nest on them — raised just above the water, exactly what a flamingo needs. An industrial site has become the thing keeping the colony alive.\nEach summer the young birds are ringed, an event volunteers travel a long way to take part in.",
  "natur_label": "Timing",
  "natur_label_en": "Timing",
  "natur_h2": "Hvornår fuglene er der",
  "natur_h2_en": "When the birds are there",
  "natur_text": "Det her er den vigtigste side af hele guiden, for det er den, der afgør, om turen bliver god.\n<b>Marts til juni er sæsonen.</b> Vandstanden er høj, fuglene yngler, og der er flest. Marts og april er typisk toppen.\n<b>Tidligt om morgenen er bedst.</b> Fuglene står tættere, lyset er blødere, og der er køligere at gå i.\n<b>Om sommeren kan søen tørre ud.</b> Sker det, flytter fuglene sig — eller forsvinder helt. Kommer I i juli eller august, så vær forberedt på, at der kan være langt til dem.\nResten af året er der stadig fugleliv, og landskabet er smukt hele året. Men vil I se det lyserøde tæppe, skal I komme om foråret.",
  "natur_text_en": "This is the most important page in the whole guide, because it decides whether the trip is a good one.\n<b>March to June is the season.</b> Water levels are high, the birds are breeding, and numbers peak — usually in March and April.\n<b>Early morning is best.</b> The birds stand closer together, the light is softer, and it is cooler to walk in.\n<b>In summer the lake can dry out.</b> When it does, the birds move — or leave entirely. If you come in July or August, be prepared for them to be a long way off.\nThe rest of the year still holds plenty of birdlife, and the landscape is beautiful year-round. But if you want the sheet of pink, come in spring.",
  "hoej_label": "Godt at vide",
  "hoej_label_en": "Good to know",
  "hoej_h2": "Tag en kikkert med",
  "hoej_h2_en": "Bring binoculars",
  "hoej_text": "Søen er stor, og fuglene står ofte langt ude. Med det blotte øje ser man et lyserødt bånd i horisonten; med en kikkert ser man fugle.",
  "hoej_text_en": "The lake is large and the birds often stand far out. With the naked eye you see a pink band on the horizon; with binoculars you see birds.",
  "praktisk_intro": "Adgangen er gratis og kræver ingen booking. Guidede ture skal derimod aftales på forhånd.",
  "praktisk_intro_en": "Access is free and requires no booking. Guided tours, however, must be arranged in advance.",
  "praktisk_grupper": "[{\"da\": [\"Entré\", \"Reservatet | Gratis\\nBesøgscenter | Gratis\\nParkering | Gratis, lige ved centret\\nBooking | Kun nødvendig til guidede ture\"], \"en\": [\"Admission\", \"The reserve | Free\\nVisitor centre | Free\\nParking | Free, right by the centre\\nBooking | Only needed for guided tours\"]}, {\"da\": [\"Besøgscentret\", \"Navn | Centro de Visitantes José Antonio Valverde\\nBeliggenhed | Cerro del Palo, ved søen\\nIndhold | Udstilling om søen og fuglelivet, kort og rådgivning\"], \"en\": [\"The visitor centre\", \"Name | Centro de Visitantes José Antonio Valverde\\nLocation | Cerro del Palo, by the lake\\nInside | Exhibition on the lake and its birdlife, maps and advice\"]}, {\"da\": [\"Sådan kører du\", \"Fra Mollina | Mod Fuente de Piedra, gennem byen, følg skiltene til Centro de Visitantes\\nFra A-92 | Afkørsel 132, derefter MA-701\"], \"en\": [\"Driving there\", \"From Mollina | Towards Fuente de Piedra, through the village, follow signs to Centro de Visitantes\\nFrom the A-92 | Exit 132, then the MA-701\"]}, {\"da\": [\"Praktisk\", \"Tid | 1–2 timer\\nMedbring | Kikkert, hat, vand\\nBedste tid på dagen | Tidlig morgen\\nBedste årstid | Marts–juni\"], \"en\": [\"Practical\", \"Time needed | 1–2 hours\\nBring | Binoculars, hat, water\\nBest time of day | Early morning\\nBest season | March–June\"]}]",
  "afstande_h2": "Ti minutter fra <em>vinejendommen</em>",
  "afstande_h2_en": "Ten minutes from <em>the estate</em>",
  "afstande_intro": "Fuente de Piedra er nabosognet til Mollina. Det er den korteste udflugt af dem alle, og den kan klares før frokost.",
  "afstande_intro_en": "Fuente de Piedra is the next village along from Mollina. It is the shortest outing of them all, and it fits in before lunch.",
  "afstande_items": "[{\"da\": [\"10 min\", \"Castillo del Alma (Mollina), i bil\"], \"en\": [\"10 min\", \"Castillo del Alma (Mollina), by car\"]}, {\"da\": [\"25 min\", \"Antequera\"], \"en\": [\"25 min\", \"Antequera\"]}, {\"da\": [\"20 min\", \"Dolmenerne i Antequera\"], \"en\": [\"20 min\", \"The Antequera Dolmens\"]}, {\"da\": [\"1 time\", \"Málaga lufthavn\"], \"en\": [\"1 hour\", \"Málaga airport\"]}]",
  "faq_items": "[{\"da\": [\"Er der flamingoer hele året?\", \"Der er fugle hele året, men antallet svinger meget. Marts til juni er ynglesæson og klart det bedste tidspunkt. Om sommeren kan søen tørre ud, og så flytter fuglene sig.\"], \"en\": [\"Are there flamingos all year?\", \"There are birds all year, but numbers vary greatly. March to June is the breeding season and clearly the best time. In summer the lake can dry out, and the birds move on.\"]}, {\"da\": [\"Koster det noget?\", \"Nej. Både reservatet, besøgscentret og parkeringen er gratis. Kun guidede ture koster.\"], \"en\": [\"Is there a charge?\", \"No. The reserve, the visitor centre and the parking are all free. Only guided tours cost anything.\"]}, {\"da\": [\"Hvor tæt kan man komme på?\", \"Fra udsigtspunkterne står fuglene typisk et godt stykke ude — derfor kikkerten. Den lille lagune i selve byen er ofte det sted, hvor man kommer tættest.\"], \"en\": [\"How close can you get?\", \"From the viewpoints the birds are usually well out — hence the binoculars. The small lagoon in the village itself is often where you get closest.\"]}, {\"da\": [\"Er det noget for børn?\", \"Ja, hvis de kan holde ud at gå stille i et kvarter. Stierne er flade og korte, og der er fugle nok til at fange opmærksomheden.\"], \"en\": [\"Is it good for children?\", \"Yes, if they can manage fifteen quiet minutes. The paths are flat and short, and there are enough birds to hold their attention.\"]}, {\"da\": [\"Skal vi booke?\", \"Ikke for at gå selv. Vil I have en guidet tur, skal den aftales i forvejen.\"], \"en\": [\"Do we need to book?\", \"Not to walk it yourselves. For a guided tour, arrange it in advance.\"]}]",
  "flere_intro": "Søen kan sagtens kombineres med Antequera og dolmenerne på én dag — alt sammen ligger inden for en halv times kørsel. Her er flere oplevelser i nærheden.",
  "flere_intro_en": "The lake combines easily with Antequera and the dolmens in a single day — all of it within half an hour''s drive. Here are more experiences nearby.",
  "cta_h2": "Flamingoer før morgenmaden",
  "cta_h2_en": "Flamingos before breakfast",
  "cta_text": "Bor man på Castillo del Alma i marts eller april, er det her den nemmeste morgen, man kan give sig selv. Ti minutter i bil, en times gang ved vandet, og hjem inden dagen rigtig er begyndt.",
  "cta_text_en": "If you are staying at Castillo del Alma in March or April, this is the easiest morning you can give yourself. Ten minutes in the car, an hour''s walk by the water, and home before the day has really started.",
  "nav_links": "[{\"tekst\": \"Søen\", \"tekst_en\": \"The lake\", \"link\": \"#sec-intro\", \"vis\": \"1\"}, {\"tekst\": \"Hvornår\", \"tekst_en\": \"When to go\", \"link\": \"#sec-natur\", \"vis\": \"1\"}, {\"tekst\": \"Praktisk\", \"tekst_en\": \"Practical\", \"link\": \"#sec-praktisk\", \"vis\": \"1\"}, {\"tekst\": \"Spørgsmål\", \"tekst_en\": \"Questions\", \"link\": \"#sec-faq\", \"vis\": \"1\"}]"
}'::jsonb)
on conflict (slug) do nothing;
