-- ─────────────────────────────────────────────────────────────────────────
-- 2026-08-04 · Seværdighed: Dolmenerne i Antequera
--
-- Én ny række i public.sevaerdigheder. Tabellen, RLS og triggeren er
-- oprettet i sql/2026-07-31-sevaerdigheder.sql — den fil skal være kørt først.
--
-- Siden bliver til /sevaerdigheder/dolmenes-antequera og /en/sevaerdigheder/dolmenes-antequera.
--
-- OPRETTES SKJULT (aktiv = false). Alle billedfelter står tomme. Læg
-- billederne ind i admin først, og sæt så Aktiv til.
--
-- Fakta hentet 4. august 2026 fra museosdeandalucia.es (gratis for EU-borgere
-- mod legitimation, 1,50 € for øvrige; lukkedage 1. og 6. januar, 1. maj samt
-- 24., 25. og 31. december) og fra dolmenesdeantequera.com (åbningstider pr.
-- sæson, mandag lukket, adgang lukkes 30 min. før). Datering og UNESCO-
-- udpegningen i 2016 fra UNESCO og fagligt opslagsværk.
--
-- BEMÆRK: Adgangen til Mengas indre har været lukket for bevaringsarbejde.
-- Det er nævnt i FAQ'en frem for som en fast oplysning, netop fordi det kan
-- være åbnet igen. Tjek før du gør siden aktiv.
--
-- Køres i Supabase SQL Editor. Idempotent — kan køres flere gange.
-- `on conflict do nothing`: køres filen igen, overskrives senere rettelser
-- i admin ikke. Vil du nulstille siden helt, så slet rækken først.
-- ─────────────────────────────────────────────────────────────────────────

insert into public.sevaerdigheder (slug, titel, titel_en, aktiv, sort_orden, indhold) values
  ('dolmenes-antequera',
   'Dolmenerne i Antequera',
   'The Antequera Dolmens',
   false,
   80,
   '{
  "nav_back": "← Tilbage til forsiden",
  "nav_back_en": "← Back to home",
  "footer_copy": "© 2026 Castillo del Alma · Mollina, Málaga · Alle rettigheder forbeholdes",
  "footer_copy_en": "© 2026 Castillo del Alma · Mollina, Málaga · All rights reserved",
  "hero_image": "",
  "social_image": "",
  "intro_image": "",
  "historie_image": "",
  "natur_image": "",
  "hoej_image": "",
  "intro_billedtekst": "",
  "intro_billedtekst_en": "",
  "historie_billedtekst": "",
  "historie_billedtekst_en": "",
  "natur_billedtekst": "",
  "natur_billedtekst_en": "",
  "hoej_billedtekst": "",
  "hoej_billedtekst_en": "",
  "strip1_images": "[]",
  "strip1_top": "2",
  "strip1_bund": "2",
  "strip2_images": "[]",
  "strip2_top": "2",
  "strip2_bund": "2",
  "strip3_images": "[]",
  "strip3_top": "2",
  "strip3_bund": "2",
  "afstande_label": "Sådan kommer du hertil",
  "afstande_label_en": "Getting there",
  "faq_label": "Spørgsmål",
  "faq_label_en": "Questions",
  "faq_h2": "Før du tager afsted",
  "faq_h2_en": "Before you go",
  "praktisk_label": "Praktiske detaljer",
  "praktisk_label_en": "Practical details",
  "praktisk_h2": "Alt du skal vide før besøget",
  "praktisk_h2_en": "Everything to know before you go",
  "flere_label": "Flere oplevelser",
  "flere_label_en": "More experiences",
  "flere_h2": "Andre seværdigheder i nærheden",
  "flere_h2_en": "Other places nearby",
  "cta_btn": "Se ejendommen",
  "cta_btn_en": "See the estate",
  "cta_link": "/udlejning",
  "lister_label": "",
  "lister_label_en": "",
  "lister_h2": "",
  "lister_h2_en": "",
  "lister_intro": "",
  "lister_intro_en": "",
  "lister_grupper": "[]",
  "hoej_punkter": "[{\"da\": [\"Menga og Viera ligger ved besøgscentret — El Romeral er 2 km væk og kræver bil\"], \"en\": [\"Menga and Viera are at the visitor centre — El Romeral is 2 km away and needs a car\"]}, {\"da\": [\"Der lukkes for adgang en halv time før lukketid\"], \"en\": [\"Admission closes half an hour before closing time\"]}, {\"da\": [\"Mandag er lukket, medmindre det er dagen før en helligdag\"], \"en\": [\"Closed on Mondays, unless it is the eve of a public holiday\"]}, {\"da\": [\"El Torcal er ikke det samme sted — der er 24 km imellem dem\"], \"en\": [\"El Torcal is not the same place — they are 24 km apart\"]}]",
  "sektion_orden": "[\"sec-print1\", \"sec-intro\", \"strip1\", \"sec-historie\", \"sec-natur\", \"sec-lister\", \"strip2\", \"sec-hoejdepunkt\", \"sec-praktisk\", \"sec-afstande\", \"strip3\", \"sec-faq\", \"sec-flere\", \"sec-cta\", \"sec-print4\"]",
  "vis_hero_stribe": "1",
  "vis_intro": "1",
  "vis_strip1": "1",
  "vis_historie": "1",
  "vis_natur": "1",
  "vis_lister": "0",
  "vis_strip2": "1",
  "vis_hoejdepunkt": "1",
  "vis_praktisk": "1",
  "vis_afstande": "1",
  "vis_strip3": "1",
  "vis_faq": "1",
  "vis_flere": "1",
  "vis_cta": "1",
  "vis_historie51": "0",
  "vis_historie52": "0",
  "vis_historie53": "0",
  "vis_historie54": "0",
  "vis_print1": "1",
  "vis_print2": "0",
  "vis_print3": "0",
  "vis_print4": "0",
  "intro_layout": "hoejre",
  "intro_bredde": "normal",
  "historie_layout": "venstre",
  "historie_bredde": "normal",
  "natur_layout": "hoejre",
  "natur_bredde": "normal",
  "hoej_layout": "venstre",
  "hoej_bredde": "normal",
  "seo_title": "Dolmenerne i Antequera — verdensarv 20 minutter fra Mollina | Castillo del Alma",
  "seo_title_en": "The Antequera Dolmens — World Heritage 20 minutes from Mollina | Castillo del Alma",
  "seo_desc": "Menga, Viera og El Romeral er ældre end pyramiderne og står på UNESCOs verdensarvsliste. Åbningstider, gratis entré for EU-borgere og hvad du skal vide før besøget.",
  "seo_desc_en": "Menga, Viera and El Romeral are older than the pyramids and on the UNESCO World Heritage list. Opening hours, free entry for EU citizens and what to know before you go.",
  "hero_eyebrow": "Antequera · Málaga · UNESCO verdensarv",
  "hero_eyebrow_en": "Antequera · Málaga · UNESCO World Heritage",
  "hero_h1": "Dolmenerne i<br>Antequera",
  "hero_h1_en": "The Antequera<br>Dolmens",
  "hero_lede": "Tre stengrave, der blev rejst før pyramiderne i Egypten — og som stadig står tyve minutter fra ejendommen.",
  "hero_lede_en": "Three stone tombs raised before the pyramids of Egypt — still standing twenty minutes from the estate.",
  "hero_scroll": "Se stedet",
  "hero_scroll_en": "See the site",
  "hero_meta": "[{\"da\": [\"Bygget omkring 3800 f.Kr.\"], \"en\": [\"Built around 3800 BC\"]}, {\"da\": [\"UNESCO verdensarv siden 2016\"], \"en\": [\"UNESCO World Heritage since 2016\"]}, {\"da\": [\"20 minutter fra ejendommen\"], \"en\": [\"20 minutes from the estate\"]}]",
  "intro_label": "Hvad det er",
  "intro_label_en": "What it is",
  "intro_h2": "Ældre end pyramiderne",
  "intro_h2_en": "Older than the pyramids",
  "intro_lede": "Menga-dolmenen blev rejst omkring 3800 f.Kr. Da de første sten blev slæbt på plads, var der endnu ingen pyramider i Egypten og ingen Stonehenge i England.",
  "intro_lede_en": "The Menga dolmen was raised around 3800 BC. When the first stones were dragged into place, there were no pyramids in Egypt and no Stonehenge in England.",
  "intro_text": "Anlægget består af tre monumenter: <b>Menga</b> og <b>Viera</b>, der ligger få meter fra hinanden ved besøgscentret, og <b>tholos''en El Romeral</b>, som ligger omkring to kilometer derfra og kræver at man kører.\nMenga er den største. Dækstenene vejer op mod 180 tons, og hvordan de blev flyttet uden hjul og uden metalværktøj, er stadig et åbent spørgsmål.\nDet hele er gratis for EU-borgere, og der går sjældent mere end halvanden time med at se det. Det gør det til en af de nemmeste udflugter herfra — og en af dem, gæsterne bliver mest overraskede over.",
  "intro_text_en": "The site consists of three monuments: <b>Menga</b> and <b>Viera</b>, standing metres apart beside the visitor centre, and the <b>tholos of El Romeral</b>, about two kilometres away and best reached by car.\nMenga is the largest. Its capstones weigh up to 180 tonnes, and how they were moved without wheels or metal tools remains an open question.\nEntry is free for EU citizens, and it rarely takes more than an hour and a half. That makes it one of the easiest outings from here — and one of the ones guests are most surprised by.",
  "historie_label": "Historien",
  "historie_label_en": "The history",
  "historie_h2": "Tre grave, tre tidsaldre",
  "historie_h2_en": "Three tombs, three ages",
  "historie_text": "Længe troede man, at de tre monumenter var bygget i samme periode. Nyere forskning peger på noget andet: Menga og Viera stammer fra omkring 3800 f.Kr., mens El Romeral først blev rejst omkring 1800 f.Kr. — næsten to årtusinder senere.\nDe er også bygget forskelligt. Menga og Viera er gangbygninger af opretstående sten med vandrette dæksten. El Romeral er en <em>tholos</em> med falsk kuppel, en teknik der hører til en helt anden byggetradition, forbundet med Los Millares-kulturen mere end 200 kilometer mod øst.\nAnlægget kom på UNESCOs verdensarvsliste i 2016 — ikke kun for gravene, men for helheden. To naturmonumenter er en del af udpegningen: klippen Peña de los Enamorados og bjerglandskabet El Torcal.",
  "historie_text_en": "For a long time the three monuments were thought to be contemporaries. More recent research points elsewhere: Menga and Viera date to around 3800 BC, while El Romeral was not built until around 1800 BC — nearly two millennia later.\nThey are built differently too. Menga and Viera are passage tombs of upright stones with horizontal capstones. El Romeral is a <em>tholos</em> with a false dome, a technique belonging to an entirely different tradition linked to the Los Millares culture more than 200 kilometres to the east.\nThe site joined the UNESCO World Heritage list in 2016 — not only for the tombs, but for the whole. Two natural monuments form part of the designation: the Peña de los Enamorados rock and the limestone landscape of El Torcal.",
  "natur_label": "Det mærkelige ved stedet",
  "natur_label_en": "The strange part",
  "natur_h2": "Graven, der vender den forkerte vej",
  "natur_h2_en": "The tomb that faces the wrong way",
  "natur_text": "Næsten alle dolmener omkring Middelhavet er orienteret mod noget på himlen — typisk solopgangen ved jævndøgn. Viera er det: den peger mod øst og mod den opgående sol.\nMenga gør ikke. Menga peger mod <b>Peña de los Enamorados</b>, den markante klippe der rejser sig af sletten nogle kilometer væk. Det er blandt de ganske få dolmener i hele regionen, der er rettet mod et sted i landskabet frem for mod himlen.\nInde i klippen findes Matacabras-hulen med klippemalerier fra samme tid. Det er svært at se det som et tilfælde — men hvad de mennesker mente med det, ved vi ikke.\nEl Romeral vender en tredje vej: mod El Torcal.",
  "natur_text_en": "Almost every dolmen around the Mediterranean is oriented towards something in the sky — typically sunrise at the equinox. Viera is: it points east, towards the rising sun.\nMenga does not. Menga points at the <b>Peña de los Enamorados</b>, the striking rock that rises from the plain a few kilometres away. It is among the very few dolmens in the region aligned to a place in the landscape rather than to the sky.\nInside that rock is the Matacabras shelter, holding cave paintings from the same era. It is hard to read as coincidence — but what those people meant by it, we do not know.\nEl Romeral faces a third way: towards El Torcal.",
  "hoej_label": "Godt at vide",
  "hoej_label_en": "Good to know",
  "hoej_h2": "Fire ting, der gør besøget bedre",
  "hoej_h2_en": "Four things that make the visit better",
  "hoej_text": "Stedet er lille og let at gå til, men der er et par ting, det er ærgerligt at opdage først, når man står der.",
  "hoej_text_en": "The site is small and easy to walk, but there are a few things it is a shame to discover only once you are standing there.",
  "praktisk_intro": "Tal og tider er hentet i august 2026 fra det officielle anlæg. Åbningstiderne skifter fire gange om året, så tjek dem før I kører.",
  "praktisk_intro_en": "Figures and times were taken in August 2026 from the official site. Opening hours change four times a year, so check before you drive out.",
  "praktisk_grupper": "[{\"da\": [\"Entré\", \"EU-borgere | Gratis mod legitimation\\nØvrige besøgende | 1,50 €\\nBooking | Ikke nødvendig for almindeligt besøg\"], \"en\": [\"Admission\", \"EU citizens | Free with ID\\nOther visitors | €1.50\\nBooking | Not required for a standard visit\"]}, {\"da\": [\"Åbningstider\", \"Tirsdag–torsdag | 9.00–18.00\\nFredag–lørdag | 9.00–21.00 (forår og forsommer)\\nSøndag og helligdage | 9.00–15.00\\nMandag | Lukket\\nSommer | Kortere tider — tjek før afgang\"], \"en\": [\"Opening hours\", \"Tuesday–Thursday | 9.00–18.00\\nFriday–Saturday | 9.00–21.00 (spring and early summer)\\nSunday and holidays | 9.00–15.00\\nMonday | Closed\\nSummer | Shorter hours — check before you go\"]}, {\"da\": [\"Lukkedage 2026\", \"Januar | 1. og 6.\\nMaj | 1.\\nDecember | 24., 25. og 31.\"], \"en\": [\"Closed in 2026\", \"January | 1 and 6\\nMay | 1\\nDecember | 24, 25 and 31\"]}, {\"da\": [\"Praktisk\", \"Tid | Regn med 1–1,5 time\\nParkering | Gratis ved besøgscentret\\nTilgængelighed | Anlægget er gjort kørestolsvenligt\\nGuidet tur | Kan aftales på forhånd via anlæggets e-mail\"], \"en\": [\"Practical\", \"Time needed | Allow 1–1.5 hours\\nParking | Free at the visitor centre\\nAccessibility | The site has been made wheelchair-friendly\\nGuided tour | Can be arranged in advance by email\"]}]",
  "afstande_h2": "Tyve minutter fra <em>vinejendommen</em>",
  "afstande_h2_en": "Twenty minutes from <em>the estate</em>",
  "afstande_intro": "Dolmenerne ligger i udkanten af Antequera, lige ved indfaldsvejen. Det er den korteste udflugt, vi har — og den kan sagtens klares på en formiddag.",
  "afstande_intro_en": "The dolmens sit on the edge of Antequera, right by the approach road. It is the shortest outing we have — and it fits easily into a morning.",
  "afstande_items": "[{\"da\": [\"20 min\", \"Castillo del Alma (Mollina), i bil\"], \"en\": [\"20 min\", \"Castillo del Alma (Mollina), by car\"]}, {\"da\": [\"5 min\", \"Antequera centrum\"], \"en\": [\"5 min\", \"Central Antequera\"]}, {\"da\": [\"30 min\", \"El Torcal de Antequera\"], \"en\": [\"30 min\", \"El Torcal de Antequera\"]}, {\"da\": [\"55 min\", \"Málaga lufthavn\"], \"en\": [\"55 min\", \"Málaga airport\"]}]",
  "faq_items": "[{\"da\": [\"Er det virkelig ældre end pyramiderne?\", \"Ja. Menga dateres til omkring 3800 f.Kr. Den ældste egyptiske pyramide, trinpyramiden i Saqqara, er fra omkring 2650 f.Kr. Der er altså over tusind år imellem dem.\"], \"en\": [\"Is it really older than the pyramids?\", \"Yes. Menga is dated to around 3800 BC. The oldest Egyptian pyramid, the step pyramid at Saqqara, dates to around 2650 BC. There are over a thousand years between them.\"]}, {\"da\": [\"Hvor lang tid skal vi sætte af?\", \"Halvanden time rækker til det hele, inklusive turen ud til El Romeral. Vil I kombinere med frokost i Antequera, så læg to en halv time.\"], \"en\": [\"How long should we allow?\", \"An hour and a half covers everything, including the drive out to El Romeral. If you want to add lunch in Antequera, allow two and a half.\"]}, {\"da\": [\"Koster det noget?\", \"Ikke for EU-borgere — der er gratis adgang mod legitimation. Øvrige besøgende betaler 1,50 €.\"], \"en\": [\"Is there a charge?\", \"Not for EU citizens — entry is free with ID. Other visitors pay €1.50.\"]}, {\"da\": [\"Kan man komme ind i gravene?\", \"Normalt ja, og det er dét, der gør besøget. Men adgangen til Mengas indre har været lukket i perioder på grund af bevaringsarbejde. Tjek anlæggets hjemmeside samme uge, I tager afsted.\"], \"en\": [\"Can you go inside the tombs?\", \"Normally yes, and that is what makes the visit. But access to the interior of Menga has been closed at times for conservation work. Check the site''s website the same week you plan to go.\"]}, {\"da\": [\"Er det noget for børn?\", \"Ja, hvis de kan lide huler. Det er mørkt, køligt og stort inde i Menga, og turen er kort nok til, at tålmodigheden holder.\"], \"en\": [\"Is it good for children?\", \"Yes, if they like caves. It is dark, cool and vast inside Menga, and the visit is short enough to hold their patience.\"]}, {\"da\": [\"Er El Torcal det samme sted?\", \"Nej. El Torcal er en del af den samme UNESCO-udpegning, men ligger 24 kilometer væk. Begge dele på én dag kan lade sig gøre, men det bliver en fuld dag.\"], \"en\": [\"Is El Torcal the same place?\", \"No. El Torcal is part of the same UNESCO designation but lies 24 kilometres away. Both in one day is possible, but it makes for a full day.\"]}]",
  "flere_intro": "Dolmenerne, El Torcal og Peña de los Enamorados hører til samme landskab og kan kombineres på en enkelt dag. Her er flere oplevelser inden for kort køreafstand fra Castillo del Alma.",
  "flere_intro_en": "The dolmens, El Torcal and the Peña de los Enamorados belong to the same landscape and can be combined in a single day. Here are more experiences within a short drive of Castillo del Alma.",
  "cta_h2": "Verdensarv en formiddag væk",
  "cta_h2_en": "World Heritage, a morning away",
  "cta_text": "Et ophold på Castillo del Alma er også adgangen til et landskab, hvor mennesker har bygget i seks tusind år. Dolmenerne er tyve minutter væk — tæt nok til, at man kan tage derud efter morgenmaden og være hjemme til frokost.",
  "cta_text_en": "A stay at Castillo del Alma is also access to a landscape where people have been building for six thousand years. The dolmens are twenty minutes away — close enough to go after breakfast and be home for lunch.",
  "nav_links": "[{\"tekst\": \"Stedet\", \"tekst_en\": \"The site\", \"link\": \"#sec-intro\", \"vis\": \"1\"}, {\"tekst\": \"Historien\", \"tekst_en\": \"History\", \"link\": \"#sec-historie\", \"vis\": \"1\"}, {\"tekst\": \"Praktisk\", \"tekst_en\": \"Practical\", \"link\": \"#sec-praktisk\", \"vis\": \"1\"}, {\"tekst\": \"Spørgsmål\", \"tekst_en\": \"Questions\", \"link\": \"#sec-faq\", \"vis\": \"1\"}]"
}'::jsonb)
on conflict (slug) do nothing;
