-- ─────────────────────────────────────────────────────────────────────────
-- 2026-08-04 · Seværdighed: Ronda
--
-- Én ny række i public.sevaerdigheder. Tabellen, RLS og triggeren er
-- oprettet i sql/2026-07-31-sevaerdigheder.sql — den fil skal være kørt først.
--
-- Siden bliver til /sevaerdigheder/ronda og /en/sevaerdigheder/ronda.
--
-- OPRETTES SKJULT (aktiv = false). Alle billedfelter står tomme. Læg
-- billederne ind i admin først, og sæt så Aktiv til.
--
-- Fakta hentet 4. august 2026. Plaza de Toros opført 1779-1785 for Real
-- Maestranza de Caballería (grundlagt 1485), blandt de første helt i sten,
-- overdækkede pladser hele vejen rundt; åbningstider fra rmcr.org (nov-feb
-- 10-18, apr-sep 10-20). Puente Nuevo: forgængeren styrtede sammen i 1741,
-- den nuværende bro bygget 1751-1793.
--
-- PRISER ER MED VILJE UDELADT. Kilderne oplyser alt fra 8,50 € til 14 €
-- afhængigt af audioguide og billettype, og de er ikke enige. Siden henviser
-- i stedet til at købe på stedet. Hellere ingen pris end en forkert.
--
-- Formuleringen om arenaen er holdt neutral: bygningen beskrives, og det
-- overlades til den besøgende, om et besøg er noget for dem.
--
-- Køres i Supabase SQL Editor. Idempotent — kan køres flere gange.
-- `on conflict do nothing`: køres filen igen, overskrives senere rettelser
-- i admin ikke. Vil du nulstille siden helt, så slet rækken først.
-- ─────────────────────────────────────────────────────────────────────────

insert into public.sevaerdigheder (slug, titel, titel_en, aktiv, sort_orden, indhold) values
  ('ronda',
   'Ronda',
   'Ronda',
   false,
   100,
   '{
  "nav_back": "← Tilbage til forsiden",
  "nav_back_en": "← Back to home",
  "footer_copy": "© 2026 Castillo del Alma · Mollina, Málaga · Alle rettigheder forbeholdes",
  "footer_copy_en": "© 2026 Castillo del Alma · Mollina, Málaga · All rights reserved",
  "hero_image": "",
  "social_image": "",
  "intro_image": "",
  "historie_image": "",
  "natur_image": "",
  "hoej_image": "",
  "intro_billedtekst": "",
  "intro_billedtekst_en": "",
  "historie_billedtekst": "",
  "historie_billedtekst_en": "",
  "natur_billedtekst": "",
  "natur_billedtekst_en": "",
  "hoej_billedtekst": "",
  "hoej_billedtekst_en": "",
  "strip1_images": "[]",
  "strip1_top": "2",
  "strip1_bund": "2",
  "strip2_images": "[]",
  "strip2_top": "2",
  "strip2_bund": "2",
  "strip3_images": "[]",
  "strip3_top": "2",
  "strip3_bund": "2",
  "afstande_label": "Sådan kommer du hertil",
  "afstande_label_en": "Getting there",
  "faq_label": "Spørgsmål",
  "faq_label_en": "Questions",
  "faq_h2": "Før du tager afsted",
  "faq_h2_en": "Before you go",
  "praktisk_label": "Praktiske detaljer",
  "praktisk_label_en": "Practical details",
  "praktisk_h2": "Alt du skal vide før besøget",
  "praktisk_h2_en": "Everything to know before you go",
  "flere_label": "Flere oplevelser",
  "flere_label_en": "More experiences",
  "flere_h2": "Andre seværdigheder i nærheden",
  "flere_h2_en": "Other places nearby",
  "cta_btn": "Se ejendommen",
  "cta_btn_en": "See the estate",
  "cta_link": "/udlejning",
  "lister_label": "",
  "lister_label_en": "",
  "lister_h2": "",
  "lister_h2_en": "",
  "lister_intro": "",
  "lister_intro_en": "",
  "lister_grupper": "[]",
  "hoej_punkter": "[{\"da\": [\"Busserne kommer typisk mellem kl. 11 og 16 — kom før eller bliv til efter\"], \"en\": [\"The coaches typically come between 11am and 4pm — arrive before, or stay until after\"]}, {\"da\": [\"Sen eftermiddag er det bedste lys på broen, og de fleste er kørt igen\"], \"en\": [\"Late afternoon gives the best light on the bridge, and most have left\"]}, {\"da\": [\"Parkér uden for centrum og gå ind — gaderne omkring broen er smalle og fyldte\"], \"en\": [\"Park outside the centre and walk in — the streets around the bridge are narrow and full\"]}, {\"da\": [\"Stien ned i kløften giver den udsigt, folk tror de får oppe fra broen\"], \"en\": [\"The path into the gorge gives the view people think they will get from the bridge\"]}]",
  "sektion_orden": "[\"sec-print1\", \"sec-intro\", \"strip1\", \"sec-historie\", \"sec-natur\", \"sec-lister\", \"strip2\", \"sec-hoejdepunkt\", \"sec-praktisk\", \"sec-afstande\", \"strip3\", \"sec-faq\", \"sec-flere\", \"sec-cta\", \"sec-print4\"]",
  "vis_hero_stribe": "1",
  "vis_intro": "1",
  "vis_strip1": "1",
  "vis_historie": "1",
  "vis_natur": "1",
  "vis_lister": "0",
  "vis_strip2": "1",
  "vis_hoejdepunkt": "1",
  "vis_praktisk": "1",
  "vis_afstande": "1",
  "vis_strip3": "1",
  "vis_faq": "1",
  "vis_flere": "1",
  "vis_cta": "1",
  "vis_historie51": "0",
  "vis_historie52": "0",
  "vis_historie53": "0",
  "vis_historie54": "0",
  "vis_print1": "1",
  "vis_print2": "0",
  "vis_print3": "0",
  "vis_print4": "0",
  "intro_layout": "hoejre",
  "intro_bredde": "normal",
  "historie_layout": "venstre",
  "historie_bredde": "normal",
  "natur_layout": "hoejre",
  "natur_bredde": "normal",
  "hoej_layout": "venstre",
  "hoej_bredde": "normal",
  "seo_title": "Ronda — byen over kløften, 1 t 15 fra Mollina | Castillo del Alma",
  "seo_title_en": "Ronda — the town above the gorge, 1 h 15 from Mollina | Castillo del Alma",
  "seo_desc": "Puente Nuevo, El Tajo-kløften og en af Spaniens ældste tyrefægterarenaer. Hvornår du skal komme, hvor du parkerer, og hvordan du undgår busturisterne.",
  "seo_desc_en": "Puente Nuevo, the El Tajo gorge and one of Spain''s oldest bullrings. When to come, where to park, and how to avoid the coach crowds.",
  "hero_eyebrow": "Ronda · Málaga · Serranía de Ronda",
  "hero_eyebrow_en": "Ronda · Málaga · Serranía de Ronda",
  "hero_h1": "Ronda",
  "hero_h1_en": "Ronda",
  "hero_lede": "En by bygget på kanten af en hundrede meter dyb kløft — og en bro, der binder de to halvdele sammen.",
  "hero_lede_en": "A town built on the edge of a hundred-metre gorge — and a bridge holding the two halves together.",
  "hero_scroll": "Byen",
  "hero_scroll_en": "The town",
  "hero_meta": "[{\"da\": [\"Puente Nuevo, færdig i 1793\"], \"en\": [\"Puente Nuevo, completed in 1793\"]}, {\"da\": [\"Arenaen fra 1785\"], \"en\": [\"The bullring, 1785\"]}, {\"da\": [\"1 t 15 fra ejendommen\"], \"en\": [\"1 h 15 from the estate\"]}]",
  "intro_label": "Hvad det er",
  "intro_label_en": "What it is",
  "intro_h2": "Byen der er skåret i to",
  "intro_h2_en": "The town cut in two",
  "intro_lede": "El Tajo-kløften skærer gennem Ronda i hele byens længde. På den ene side ligger den gamle maurisk by, på den anden den nyere. Imellem dem står Puente Nuevo — broen, der er blevet hele Andalusiens postkort.",
  "intro_lede_en": "The El Tajo gorge cuts through Ronda along the town''s full length. On one side lies the old Moorish town, on the other the newer one. Between them stands the Puente Nuevo — the bridge that has become Andalusia''s postcard.",
  "intro_text": "Ronda er en af de mest besøgte byer i indlandet, og det mærkes midt på dagen. Men byen er større end sit ene fotografi, og går man tre gader væk fra broen, har man den næsten for sig selv.\nDet meste kan gås. Broen, arenaen, de arabiske bade og udsigtspunkterne ligger inden for et kvarters gang fra hinanden.\nDer er halvanden times kørsel fra ejendommen — den længste af vores udflugter, men også den, der føles mest som en rigtig rejsedag.",
  "intro_text_en": "Ronda is one of the most visited towns inland, and you feel it in the middle of the day. But the town is bigger than its one photograph, and three streets away from the bridge you almost have it to yourself.\nMost of it is walkable. The bridge, the bullring, the Arab baths and the viewpoints all sit within a fifteen-minute walk of one another.\nIt is an hour and a quarter''s drive from the estate — our longest outing, but also the one that feels most like a proper day out.",
  "historie_label": "Broen",
  "historie_label_en": "The bridge",
  "historie_h2": "Toogfyrre år at bygge",
  "historie_h2_en": "Forty-two years to build",
  "historie_text": "Der havde stået en bro før. Den blev færdig i 1735 og styrtede sammen seks år senere. Man begyndte forfra i 1751, og denne gang tog det toogfyrre år.\nResultatet står der endnu: knap hundrede meter fra kløftbunden til rækværket, bygget af sten hentet i selve kløften.\nInde i brofundamentet er der et rum, som har været brugt til forskellige ting gennem tiden — blandt andet som fængsel. I dag rummer det en lille udstilling om byggeriet.\nUdsigten fra broen er den, alle kommer efter. Men den bedste udsigt <em>til</em> broen får man nedefra, fra stien der snor sig ned i kløften.",
  "historie_text_en": "There had been a bridge before. It was finished in 1735 and collapsed six years later. Work began again in 1751, and this time it took forty-two years.\nThe result is still standing: nearly a hundred metres from the floor of the gorge to the parapet, built from stone quarried in the gorge itself.\nInside the bridge''s foundation is a chamber that has served various purposes over time — among them a prison. Today it holds a small exhibition about the construction.\nThe view from the bridge is what everyone comes for. But the best view <em>of</em> the bridge is from below, on the path that winds down into the gorge.",
  "natur_label": "Arenaen",
  "natur_label_en": "The bullring",
  "natur_h2": "En af Spaniens ældste",
  "natur_h2_en": "One of Spain''s oldest",
  "natur_text": "Plaza de Toros blev bygget mellem 1779 og 1785 for Real Maestranza de Caballería, et rideselskab grundlagt i 1485.\nDen kaldes ofte Spaniens ældste. Det er en tilsnigelse — men den er blandt de første, der er opført helt i sten frem for sten og tegl, og den er usædvanlig ved at have overdækkede pladser hele vejen rundt.\nI dag bruges den kun til ganske få arrangementer om året. Resten af tiden er den museum, og man kan gå ud i selve arenaen, ned i tyrefoldene og ind i stalden.\nOm man har lyst til at besøge en tyrefægterarena, er en personlig sag. Bygningen i sig selv er værd at se, og udstillingen handler i høj grad om ridekunst og byens historie.",
  "natur_text_en": "The Plaza de Toros was built between 1779 and 1785 for the Real Maestranza de Caballería, an order of horsemanship founded in 1485.\nIt is often called Spain''s oldest. That overstates it — but it is among the first built entirely in stone rather than stone and brick, and it is unusual in having covered seating all the way round.\nToday it hosts only a handful of events a year. The rest of the time it is a museum, and you can walk out into the ring itself, down into the bullpens and through the stables.\nWhether you want to visit a bullring is a personal matter. The building itself is worth seeing, and the exhibition is largely about horsemanship and the town''s history.",
  "hoej_label": "Godt at vide",
  "hoej_label_en": "Good to know",
  "hoej_h2": "Sådan undgår du busserne",
  "hoej_h2_en": "How to avoid the coaches",
  "hoej_text": "Ronda får dagsture fra hele kysten, og de ankommer i et forudsigeligt mønster. Ved I det, kan I lægge dagen udenom.",
  "hoej_text_en": "Ronda receives day trips from all along the coast, and they arrive in a predictable pattern. Knowing it lets you plan around them.",
  "praktisk_intro": "Priser og åbningstider er hentet i august 2026 og ændrer sig. Tjek de officielle sider, hvis besøget står og falder med det.",
  "praktisk_intro_en": "Prices and opening hours were taken in August 2026 and do change. Check the official sites if your visit depends on them.",
  "praktisk_grupper": "[{\"da\": [\"Plaza de Toros\", \"Åbent | Alle dage\\nNovember–februar | 10.00–18.00\\nApril–september | 10.00–20.00\\nMarts og oktober | Derimellem\\nBillet | Købes på stedet, audioguide kan tilkøbes\\nLukket | Ugen omkring feria i september\"], \"en\": [\"Plaza de Toros\", \"Open | Every day\\nNovember–February | 10.00–18.00\\nApril–September | 10.00–20.00\\nMarch and October | In between\\nTickets | On site, audio guide available\\nClosed | The week around the September feria\"]}, {\"da\": [\"Puente Nuevo\", \"Broen | Frit tilgængelig hele døgnet\\nUdstillingen i brofundamentet | Billet, kortere åbningstid\\nStien ned i kløften | Gratis, stejl på vej op\"], \"en\": [\"Puente Nuevo\", \"The bridge | Free and open at all hours\\nExhibition inside the foundation | Ticketed, shorter hours\\nPath into the gorge | Free, steep on the way back up\"]}, {\"da\": [\"Andet værd at se\", \"Baños Árabes | Arabiske bade fra 1200-tallet, blandt de bedst bevarede i Spanien\\nCasa del Rey Moro | Have og trappe ned gennem klippen\\nAlameda del Tajo | Park med udsigt, og hvor lokale går tur\"], \"en\": [\"Also worth seeing\", \"Baños Árabes | 13th-century Arab baths, among the best preserved in Spain\\nCasa del Rey Moro | Garden and a stairway cut down through the rock\\nAlameda del Tajo | Park with a view, where locals take their evening walk\"]}, {\"da\": [\"Praktisk\", \"Tid | En halv til en hel dag\\nParkering | Betalingsparkering uden for centrum\\nTerræn | Brostens- og bakkegader, gode sko\\nBedste årstid | April–maj og september–oktober\"], \"en\": [\"Practical\", \"Time needed | Half a day to a full day\\nParking | Paid parking outside the centre\\nTerrain | Cobbles and hills, wear proper shoes\\nBest season | April–May and September–October\"]}]",
  "afstande_h2": "Halvanden time fra <em>vinejendommen</em>",
  "afstande_h2_en": "Just over an hour from <em>the estate</em>",
  "afstande_intro": "Turen går vestpå gennem bjergene og er smuk hele vejen. Det er vores længste udflugt, men vejen er en del af oplevelsen.",
  "afstande_intro_en": "The drive runs west through the mountains and is beautiful the whole way. It is our longest outing, but the road is part of the experience.",
  "afstande_items": "[{\"da\": [\"1 t 15\", \"Castillo del Alma (Mollina), i bil\"], \"en\": [\"1 h 15\", \"Castillo del Alma (Mollina), by car\"]}, {\"da\": [\"1 time\", \"Antequera\"], \"en\": [\"1 hour\", \"Antequera\"]}, {\"da\": [\"1 t 30\", \"Málaga lufthavn\"], \"en\": [\"1 h 30\", \"Málaga airport\"]}, {\"da\": [\"1 t 45\", \"Sevilla\"], \"en\": [\"1 h 45\", \"Seville\"]}]",
  "faq_items": "[{\"da\": [\"Kan man nå Ronda på en halv dag?\", \"Det kan lige lade sig gøre, men det bliver stresset. Kørslen alene er to en halv time frem og tilbage. Læg en hel dag, og bliv til sidst på eftermiddagen, hvor lyset er bedst.\"], \"en\": [\"Can Ronda be done in half a day?\", \"Just about, but it will feel rushed. The drive alone is two and a half hours there and back. Give it a full day and stay into the late afternoon, when the light is best.\"]}, {\"da\": [\"Hvornår er der færrest mennesker?\", \"Før kl. 11 og efter kl. 16. Dagsbusserne fra kysten ankommer og tager afsted i et ret fast mønster, og byen skifter karakter, når de er væk.\"], \"en\": [\"When is it quietest?\", \"Before 11am and after 4pm. The day coaches from the coast arrive and leave on a fairly fixed pattern, and the town changes character once they have gone.\"]}, {\"da\": [\"Skal man ind i tyrefægterarenaen?\", \"Det er en personlig beslutning. Bygningen er arkitektonisk bemærkelsesværdig, og udstillingen handler mest om ridekunst og byens historie. Der er ingen tyrefægtning at overvære — arenaen bruges kun til ganske få arrangementer om året.\"], \"en\": [\"Should you go inside the bullring?\", \"That is a personal decision. The building is architecturally remarkable, and the exhibition is largely about horsemanship and the town''s history. There is no bullfighting to watch — the ring is used for only a handful of events a year.\"]}, {\"da\": [\"Hvor får man det berømte billede af broen?\", \"Ikke fra broen selv. Gå ned ad stien i kløften på nordsiden, eller ud til udsigtspunktet ved Casa del Rey Moro. Nedefra ser man hele konstruktionen.\"], \"en\": [\"Where do you get the famous photo of the bridge?\", \"Not from the bridge itself. Take the path down into the gorge on the north side, or walk out to the viewpoint by the Casa del Rey Moro. From below you see the whole structure.\"]}, {\"da\": [\"Er der langt at gå?\", \"Nej, men det er kuperet. Alt det centrale ligger inden for et kvarters gang, og der er brosten og bakker. Stien ned i kløften er stejl på vej op.\"], \"en\": [\"Is there much walking?\", \"No, but it is hilly. Everything central is within a fifteen-minute walk, over cobbles and slopes. The path into the gorge is steep on the way back up.\"]}, {\"da\": [\"Kan man kombinere Ronda med noget andet?\", \"Ikke rigtig på samme dag — der er for langt. Ronda fortjener dagen for sig selv.\"], \"en\": [\"Can Ronda be combined with something else?\", \"Not really on the same day — it is too far. Ronda deserves a day of its own.\"]}]",
  "flere_intro": "Ronda ligger vestpå og er en dag for sig. Tættere på ejendommen ligger der en række oplevelser, som kan klares på en formiddag.",
  "flere_intro_en": "Ronda lies to the west and makes a day of its own. Closer to the estate there are experiences that fit into a morning.",
  "cta_h2": "Gør Ronda til dagen, I husker",
  "cta_h2_en": "Make Ronda the day you remember",
  "cta_text": "Kør vestpå efter morgenmaden, gå byen igennem, spis sent, og vær tilbage på ejendommen til solnedgang over vinmarkerne. Det er den slags dag, et ophold her gør muligt.",
  "cta_text_en": "Drive west after breakfast, walk the town, eat late, and be back at the estate for sunset over the vines. That is the kind of day a stay here makes possible.",
  "nav_links": "[{\"tekst\": \"Byen\", \"tekst_en\": \"The town\", \"link\": \"#sec-intro\", \"vis\": \"1\"}, {\"tekst\": \"Broen\", \"tekst_en\": \"The bridge\", \"link\": \"#sec-historie\", \"vis\": \"1\"}, {\"tekst\": \"Arenaen\", \"tekst_en\": \"The bullring\", \"link\": \"#sec-natur\", \"vis\": \"1\"}, {\"tekst\": \"Praktisk\", \"tekst_en\": \"Practical\", \"link\": \"#sec-praktisk\", \"vis\": \"1\"}]"
}'::jsonb)
on conflict (slug) do nothing;
